baseURL = '/'
languageCode = 'en-us'
title = 'Benjamen Lim'
theme = 'PaperMod'
[module]
  [[module.mounts]]
    source = "images"
    target = "static/images"
  [[module.mounts]]
    source = "static"
    target = "static"

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowThumbnailOnList = true

[taxonomies]
  tag = 'tag'

[params.cover]
  hiddenInList = false
  responsiveImages = false

